### ISSUE TITLE
ST.66 vs ST.96

### ISSUE THREAD

**Issue by markushopkins** [codingatty/Plumage-py#1]
When I run plumage.py on the example registration, reg. no 2,564,831, the resulting TSDRData object reports the DiagnosticInfoXSLTFilename as ST66.xsl, but the XML coming out of the status_s66 file in https://tsdrapi.uspto.gov/ts/cd/casestatus/rn2564831/content.zip contains the mappings that exist in the ST96.xsl, so it appears this must be the file used for the transforms.  As far as I can tell though, the document root is used to determine which XSLT file should be used, and the document root for the status_s66 file (big surprise coming) maps to the ST66 tag (imagine that).  At this point, however, I lose the thread as to how the file is getting transformed correctly, since the applicable mappings are only present in ST96.xsl.

Am I making sense?

Thanks.

The TSDRData output I get for reg. no 2,564,831:
"{\"DiagnosticInfoImplementationCopyright\": \"Copyright 2014-2017 Terry Carroll\", \"RegistrationNumber\": \"2564831\", \"CurrentLocationCode\": \"40S\", \"MarkCurrentStatusDateTruncated\": \"2009-02-07\", \"CorrespondentAddressCity\": \"LOS ANGELES\", \"DiagnosticInfoImplementationURL\": \"https://github.com/codingatty/Plumage-py\", \"RegistrationDateTruncated\": \"2002-04-30\", \"CorrespondentEmailAddress\": \"\", \"ApplicationDateTruncated\": \"1996-10-15\", \"CorrespondentOrganization\": \"FULWIDER PATTON LEE & UTECHT LLP\", \"DiagnosticInfoImplementationVersion\": \"V. 1.2.0\", \"DiagnosticInfoXSLProcessorVersion\": \"1.0\", \"CorrespondentAddressGeoRegion\": \"CALIFORNIA\", \"CurrentLocationDate\": \"2007-08-21-04:00\", \"RenewalDateTruncated\": \"\", \"DiagnosticInfoImplementationDate\": \"2017-03-14\", \"LawOfficeAssignedText\": \"LAW OFFICE 102\", \"PublicationDateTruncated\": \"2002-02-05\", \"DiagnosticInfoXSLTAuthor\": \"Terry Carroll\", \"PublicationDate\": \"2002-02-05-05:00\", \"RenewalDate\": \"\", \"DiagnosticInfoXSLTURL\": \"https://github.com/codingatty/Plumage\", \"CorrespondentCountryCode\": \"US\", \"DiagnosticInfoXSLTFormat\": \"ST.66\", \"StaffOfficialTitle\": \"\", \"CorrespondentFaxNumber\": \"\", \"DiagnosticInfoExecutionDateTime\": \"2017-06-21 02:10:07\", \"ApplicationNumber\": \"75181334\", \"MarkCurrentStatusDate\": \"2009-02-07-05:00\", \"StaffName\": \"\", \"DiagnosticInfoXSLTDate\": \"2017-03-15\", \"CorrespondentAddressLine02\": \"6060 CTR DR 10TH FL\", \"DiagnosticInfoImplementationAuthor\": \"Terry Carroll\", \"DiagnosticInfoXSLTSPDXLicenseIdentifier\": \"Apache-2.0\", \"CorrespondentCombinedAddress\": \"HOWARD HUGHES CTR/6060 CTR DR 10TH FL/LOS ANGELES/CALIFORNIA/90045/US\", \"CurrentLocationDateTruncated\": \"2007-08-21\", \"MarkVerbalElementText\": \"MONTY PYTHON'S FLYING CIRCUS\", \"CorrespondentPostalCode\": \"90045\", \"DiagnosticInfoImplementationLicenseURL\": \"http://www.apache.org/licenses/LICENSE-2.0\", \"DiagnosticInfoXSLTCopyright\": \"Copyright 2014-2017 Terry Carroll\", \"RegistrationDate\": \"2002-04-30-04:00\", \"DiagnosticInfoXSLProcessorVendor\": \"libxslt\", \"CorrespondentAddressLine01\": \"HOWARD HUGHES CTR\", \"DiagnosticInfoXSLTLocation\": \"/var/task/Plumage\", \"DiagnosticInfoImplementationName\": \"Plumage-py\", \"DiagnosticInfoXSLTVersion\": \"1.1.1\", \"DiagnosticInfoXSLTLicense\": \"Apache License, version 2.0 (January 2004)\", \"RegisterCategory\": \"Principal\", \"MarkCurrentStatusExternalDescriptionText\": \"Registration cancelled because registrant did not file an acceptable declaration under Section 8.  To view all documents in this file, click on the Trademark Document Retrieval link at the top of this page.\", \"DiagnosticInfoXMLSource\": \"https://tsdrapi.uspto.gov/ts/cd/casestatus/rn2564831/content.zip\", \"ApplicationDate\": \"1996-10-15-04:00\", \"DiagnosticInfoXSLTLicenseURL\": \"http://www.apache.org/licenses/LICENSE-2.0\", \"DiagnosticInfoImplementationLicense\": \"Apache License, version 2.0 (January 2004)\", \"CorrespondentPhoneNumber\": \"\", \"DiagnosticInfoImplementationSPDXLicenseIdentifier\": \"Apache-2.0\", \"DiagnosticInfoXSLProcessorVendorURL\": \"http://xmlsoft.org/XSLT/\", \"CurrentLocationText\": \"SCANNING ON DEMAND\", \"DiagnosticInfoXSLTFilename\": \"ST66.xsl\", \"CorrespondentName\": \"I MORLEY DRUCKER\"}"

**Comment by codingatty** [comment]
Markus, thanks. I just got in from vacation yesterday, and will be looking at  this shortly.

Just so I understand, it looks like you are running the Python as it currently stands in the repository, right? I see "DiagnosticInfoImplementationVersion": "V. 1.2.0", but V.1.2.0 is not yet released.

That being said I recall discovering I had some inconsistencies in the ST.xx file Diag entries that I am not sure have been completely addressed yet.

Be aware: between 1.1.0 and 1.2.0 there will be some API changes. In release V1.1.0 and earlier, both single-instance attributes and multiple-instance attributes were kept in a single dictionary named TSDRMap. Starting with 1.2.0, TSDRMap is now a separate object, containing two dictionaries: TSDRSingle for single-valued attributes, and TSDRMulti for multi-valued attributes.

Examples of single-instance attributes are the application serial number (ApplicationNumber), the filing date (ApplicationDate), and its current status (MarkCurrentStatusExternalDescriptionText).  Examples of multiple-instance attributes are prosecution events and assignments (kept in the lists MarkEventList and AssignmentList, respectively). 

The documentation is still at a V1.1.0 level, though.

**Comment by codingatty** [comment]
Markus, I don't follow what you mean when you say that the status_st66.xml file provides inthe PTO zip file "contains the mappings that exist in the ST96.xsl". Can you give more detail, and maybe an example?

ST.66 and ST.96 are two different schemas the PTO uses or has used (and where they used ST.96, they changed from using ST.96 1_D3 to ST.96 2.2.1 about a year ago). The two Plumage XSL files are designed to produce near-identical output (other than identifying whether ST.96 or ST.66 is used), regardless of what form the PTO sends it in. So you shouldn't really be seeing things in ST.66-formatted XML that's not in ST.96, or vice-versa.

For example, for the register identification (i.e. the principal register or the supplemental register), the ST.66 schema uses the XML tag name "RegisterCategory" and uses the value "Principal" to indicate the principal register. However, although the ST.96 schema also uses the tag name "RegisterCategory", it uses "Primary" (not "Principal") to indicate the principal register. But both of the XSL files (ST66.XSL and ST96.XSL) consistently output this as "Principal".

**Comment by markushopkins** [comment]
Terry,

Yep, I'm running it as in the repo. I like to live on the edge.

Since I wrote the initial issue, I realized a few things.  

First, I realized I was only pulling data from TSDRSingle, and realized I'd been ignoring TSDRMulti, but I appreciate you mentioning it here since it was absolutely missing from the output when I created the issue.

Second, the crux of my misunderstanding (which I now believe it is, but I can't wrap my head around how the XSL files are actually working) is that in the xml file for reg. no. 2,564,831 there are multiple fields prepended with "ns2", which appears throughout the ST.96 file, and none are prepended with "tm" as appears in the ST.66 file. I've since realized that these aren't fields that end up in the output, but  I still can't figure out how the xsl files work as defined (and my hope that you might be willing to clarify is the reason I left the issue open). From my (very, very limited) understanding of XSLT, as an example, the tag being searched for using the ST.66 schema is the xml tag name "tm:ApplicationNumber" but the tag name that exists is "ApplicationNumber"... 

I'm sure I'm missing something simple, so I apologize if I've totally wasted your time.

You may also find this interesting (but it's admittedly not fully baked):
https://784zq5rhrc.execute-api.us-east-1.amazonaws.com/dev/api/v1/mark/r/2564831/MarkVerbalElementText

**Comment by codingatty** [comment]
No problem; sorry it's taken a while to respond, but between catching up with work and readjusting to a 14-hour time zone change, I've been a little swamped.

Okay, to make this clear, let's just stick to ST66; it's probably simpler to ignore ST96 altogether, except as a little coda.

In the PTO's XML file, you'll see this (I'm breaking lines up for readability):

    <Transaction xmlns:ns2="urn:us:gov:doc:uspto:trademark:status"
                 xmlns="http://www.wipo.int/standards/XMLSchema/trademarks">

This means the file uses two namespaces. Taking them in reverse order, one (` xmlns=`) is a schema administered by WIPO, `http://www.wipo.int/standards/XMLSchema/trademarks`; it is unnamed. The other  (` xmlns=ns2`) is the PTO's extensions to the WIPO definition, `urn:us:gov:doc:uspto:trademark:status`; it is named `ns2` (for "name space #2," I gather; a rather undescriptive name, but that's what they use).

In the XML file, the tag `<ApplicationNumber>` is not qualified; so it is governed by the unnamed WIPO namespace. 

Now, in the ST66.XSL file, you'll see:

    <xsl:stylesheet version="1.0" 
        xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
        xmlns:tm="http://www.wipo.int/standards/XMLSchema/trademarks"
        xmlns:pto="urn:us:gov:doc:uspto:trademark:status">

This declares three namespaces. First is `xmlns:xsl="http://www.w3.org/1999/XSL/Transform"`, which  identifies the [XSLT namespace](https://www.w3.org/1999/XSL/Transform). It's required in any XSLT file, and is traditionally named `xsl`. You'll see the other two (`http://www.wipo.int/standards/XMLSchema/trademarks` and `urn:us:gov:doc:uspto:trademark:status`) are the same namespaces as in the PTO XML file. As far as I can tell, I can't use an unnamed namespace in XSLT, so I had to assign a name at least to the WIPO schema; and as long as I was doing that, I figured I give them both descriptive names: `tm` for the WIPO trademarks schema; and `pto` for the PTO's additions.

So when my XSL refers to `<tm:TradeMark>`, it is referring to the `Trademark` tag in the `tm` namespace, which is `http://www.wipo.int/standards/XMLSchema/trademarks`; this is the unnamed namespace in the XML file, so it refers to the `<TradeMark>` element (no namespace qualification) in the PTO XML file.

Now, for some elements, I need to go into the fields defined by the PTO's extended schema. For example, to get to the register category, I use `<xsl:value-of select="pto:RegisterCategory"/>`. This says, using the `pto` namespace  (which is `urn:us:gov:doc:uspto:trademark:status` ), get the value of `RegisterCategory`. In the XML file, the namespace `urn:us:gov:doc:uspto:trademark:status` is named `ns2`, so the XSL processor looks in the XML file for the field `ns2:RegisterCategory`. 

All of this is a long-winded way of saying, `tm:foo` in the ST66.XSL file refers to `foo` in the XML file; and `pto:foo` in the ST66.XSL file refers to `ns2:foo` in the XML file.

I developed the ST.66 transform first, and then added the ST.96 later (by default, if you don't request a zip file, you get ST.96, something I didn't realize until I was underway). At the time I did the ST.96, the PTO was using ST-96 1_D3, which had the following namespace declarations:

    xmlns:com="http://www.wipo.int/standards/XMLSchema/Common/1" 
    xmlns:tmk="http://www.wipo.int/standards/XMLSchema/Trademark/1"

`com` and `tmk` were nice descriptive names, so I went with them, too:

    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:com="http://www.wipo.int/standards/XMLSchema/Common/1"
    xmlns:tmk="http://www.wipo.int/standards/XMLSchema/Trademark/1">

Then, a little over a year ago, the PTO went to ST-96 2.2.1, which was slightly different, but enough to break the ST96.XSL file. In the new-format files, the PTO went to nondescriptive namespaces, `ns1`, `ns2`, and `ns3`:

    xmlns:ns1="http://www.wipo.int/standards/XMLSchema/ST96/Common"
    xmlns:ns2="http://www.wipo.int/standards/XMLSchema/ST96/Trademark"
    xmlns:ns3="urn:us:gov:doc:uspto:trademark"> 

When I updated my ST96 XSL to handle the new format, I just used the same namespace names as the PTO:

    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:ns1="http://www.wipo.int/standards/XMLSchema/ST96/Common" 
    xmlns:ns2="http://www.wipo.int/standards/XMLSchema/ST96/Trademark" 
    xmlns:ns3="urn:us:gov:doc:uspto:trademark">

Unlike ST.66, where I had to make up a namespace ID for the unnamed namespace used in the XML file, none of the ST.96 namespaces are unnamed; so I found it simpler just to use the same namespace IDs that the PTO did. In retrospect, it may make sense to do the same for ST.66 to avoid just this kind of confusion; maybe use `unnamed` or `ns0` for the unnamed namespace.

Anyway... does this clear it up?

This was my first significant use of XSLT, and I learned and kludged a lot as I went along. I now gather that there are more elegant ways of doing this, and I plan on looking into that someday, but as long as this is working, I'm happy.

**Comment by markushopkins** [comment]
Terry,

Absolutely no apology necessary.  I really appreciate that you took the time to explain all of this to me even though clearly the "issue" was all mine, heh.  I blew right past the section of the stylesheet that *might* have made everything clear, but I suspect I still would not have understood the connection without a lot of struggle. 

In any event, I definitely get it now, thanks to your fantastic explanation.  At the very least I owe you a coffee (or your beverage of choice) next time I'm up in the bay area.  Thanks again.
